version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      DB_HOST: your_db_host
      DB_PORT: your_db_port
      DB_NAME: your_db_name
      DB_USER: your_db_user
      DB_PASSWORD: your_db_password
      SECRET_KEY: your_secret_key
    volumes:
      - .:/app